# Generated by Django 5.2.8 on 2025-11-26 04:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Work Email (if different)')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=10, null=True, verbose_name='Marital Status')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternate Phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Residential Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(default='Nigeria', max_length=100, verbose_name='Country')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality')),
                ('state_of_origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='State of Origin')),
                ('religion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Religion')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Employee ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title/Position')),
                ('level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MID', 'Mid-Level'), ('SENIOR', 'Senior'), ('LEAD', 'Lead'), ('PRINCIPAL', 'Principal')], max_length=20, null=True, verbose_name='Professional Level')),
                ('bio', models.TextField(blank=True, help_text='Brief professional description', null=True, verbose_name='Bio/About')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills', null=True, verbose_name='Skills')),
                ('languages', models.CharField(blank=True, help_text='e.g., English, Hausa, Yoruba', max_length=200, null=True, verbose_name='Languages Spoken')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit/Team')),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern'), ('PART_TIME', 'Part-Time'), ('TEMPORARY', 'Temporary')], default='PERMANENT', max_length=20, verbose_name='Contract Type')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Date Joined Company')),
                ('employee_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20, verbose_name='Employee Status')),
                ('work_schedule', models.CharField(choices=[('SHIFTS', 'Shift-based'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('FLEXIBLE', 'Flexible')], default='HYBRID', max_length=20, verbose_name='Work Schedule')),
                ('office_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Office Location')),
                ('approval_level', models.CharField(choices=[('STAFF', 'Staff (No Approval Power)'), ('SUPERVISOR', 'Supervisor'), ('DEPT_HEAD', 'Department Head'), ('DEPUTY_DIR', 'Deputy Director'), ('DIRECTOR', 'Director'), ('HR_ADMIN', 'HR Admin'), ('IT_ADMIN', 'IT Admin')], default='STAFF', max_length=20, verbose_name='Approval Level')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Number')),
                ('account_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Name')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID / NIN')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Name')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relationship')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_address', models.TextField(blank=True, null=True, verbose_name='Emergency Contact Address')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status (Can access admin)')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Reports To (Manager/Supervisor)')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'), models.Index(fields=['employee_id'], name='accounts_cu_employe_7adde6_idx'), models.Index(fields=['department'], name='accounts_cu_departm_c7799a_idx'), models.Index(fields=['approval_level'], name='accounts_cu_approva_24a576_idx')],
            },
        ),
    ]
